using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RequiredPointsForLevels : MonoBehaviour
{
    public int forWL1;
    public int forWL2;
    public int forWL3;
    public int forWL4;
    public int forWL5;
    public int forWL6;
    public int forWL7;
    public int forWL8;
    public int forWL9;
    public int forWL10;
    public int forWL11;
    public int forWL12;
    public int forWL13;
    public int forWL14;
    public int forWL15;
    public int forWL16;
    public int forWL17;
    public int forWL18;
    public int forWL19;
    public int forWL20;
    public int forWL21;
    public int forWL22;
    public int forWL23;
    public int forWL24;
    public int forWL25;
    public int forWL26;
    public int forWL27;
    public int forWL28;

    public int forWN1;
    public int forWN2;
    public int forWN3;
    public int forWN4;
    public int forWN5;
    public int forWN6;
    public int forWN7;
    public int forWN8;
    public int forWN9;
    public int forWN10;
    public int forWN11;

    public int forPL1;
    public int forPL2;
    public int forPL3;
    public int forPL4;
    public int forPL5;
    public int forPL6;
    public int forPL7;
    public int forPL8;
    public int forPL9;
    public int forPL10;
    public int forPL11;
    public int forPL12;
    public int forPL13;
    public int forPL14;
    public int forPL15;
    public int forPL16;
    public int forPL17;
    public int forPL18;
    public int forPL19;
    public int forPL20;
    public int forPL21;
    public int forPL22;
    public int forPL23;
    public int forPL24;
    public int forPL25;
    public int forPL26;
    public int forPL27;
    public int forPL28;

    public int forPN1;
    public int forPN2;
    public int forPN3;
    public int forPN4;
    public int forPN5;
    public int forPN6;
    public int forPN7;
    public int forPN8;
    public int forPN9;
    public int forPN10;
    public int forPN11;

    public int forARR1;
    public int forARR2;
    public int forARR3;
    public int forARR4;
    public int forARR5;
    public int forARR6;
    public int forARR7;
    public int forARR8;
    public int forARR9;
    public int forARR10;
    public int forARR11;
    public int forARR12;
    public int forARR13;
    public int forARR14;
    public int forARR15;
    public int forARR16;
    public int forARR17;
    public int forARR18;

    public int forPostTest;
}
